project = "lcarsstarter"
version = 1
author = "Frank Holler"
language = "de_DE.utf8"

[folder]
base = "/srv/lcarsstarter"
git = ".git"
venv = ".venv"
config = "config"
run = "run"
cmd_folder = "/usr/bin"
data = "data"

[git]
remote = "https://github.com/fholler0371/lcarsstarter.git"
folder = "lcarsstarter"
pull = true

[setup]
apt = ["nano"]
folder = ["data"]
#lcars_base_folder = "/srv/lcars"

[commands]
config = true
language = true

[helper_programms]
editor = "nano"

[[plugin]]
name = "apt"
remote = "https://github.com/fholler0371/lcars_plugin_apt.git"
pull = true
install = true

[[plugins]]
name = "status"
remote = "https://github.com/fholler0371/lcars_plugin_status.git"
pull = true
install = true
drive.root = "/dev/mmcblk0p2"
net.LAN = "eth0"
net.Wifi = "wlan0"

[[plugins]]
name = "network"
remote = "https://github.com/fholler0371/lcars_plugin_network.git"
pull = true
install = true
wifi.default = "ssid_1"
wifi.ssid_1 = "password"
wifi.ssid_2 = "password"
mode.eth0.method = "auto"
mode.eth1.method = "manual"
mode.eth1.ip = "192.168.0.10/23"
mode.eth1.gateway = "192.168.1.1"
mode.eth1.dns = "192.168.1.2"
#router.source = "wlan0"
#router.dest = "eth0"
#router.name = "lcars"
