project = "lcarsstarter"
version = 1
author = "Frank Holler"

[folder]
base = "/srv/lcarsstarter"
git = ".git"
venv = ".venv"
config = "config"

[git]
remote = "https://github.com/fholler0371/lcarsstarter.git"
