project = "lcarsstarter"
version = 1
author = "Frank Holler"

[folder]
base = "/srv/lcarsstarter"
git = ".git"
venv = ".venv"
config = "config"
run = "run"
cmd_folder = "/usr/bin"

[git]
remote = "https://github.com/fholler0371/lcarsstarter.git"
folder = "lcarsstarter"
#pull = false

