project = "lcarsstarter"
version = 1
author = "Frank Holler"
language = "de_DE.utf8"

[folder]
base = "/srv/lcarsstarter"
git = ".git"
venv = ".venv"
config = "config"
run = "run"
cmd_folder = "/usr/bin"

[git]
remote = "https://github.com/fholler0371/lcarsstarter.git"
folder = "lcarsstarter"
#pull = false

[apt]
install = ["nano"]

[commands]
config = true
language = true

[helper_programms]
editor = "nano"