project = "lcarsstarter"
version = 1
author = "Frank Holler"
language = "de_DE.utf8"

[folder]
base = "/srv/lcarsstarter"
git = ".git"
venv = ".venv"
config = "config"
run = "run"
cmd_folder = "/usr/bin"
data = "data"

[git]
remote = "https://github.com/fholler0371/lcarsstarter.git"
folder = "lcarsstarter"
#pull = false

[setup]
apt = ["nano"]
folder = ["data"]

[commands]
config = true
language = true

[helper_programms]
editor = "nano"

[[plugin]]
name = "apt"
remote = "https://github.com/fholler0371/lcars_plugin_apt.git"
pull = true
install = true